# Generated by Django 6.0.5 on 2026-05-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcView', '0002_delete_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('students_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funcView.students')),
                ('National_Id', models.IntegerField()),
            ],
            bases=('funcView.students',),
        ),
    ]
