# Generated by Django 6.0.5 on 2026-05-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcView', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizen',
        ),
    ]
