# Generated by Django 6.0.5 on 2026-05-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcView', '0002_delete_citizen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animals',
        ),
        migrations.DeleteModel(
            name='Fruits',
        ),
    ]
